name: Run Data Script

on:
  workflow_dispatch:
  schedule:
  - cron: "30 8,20 * * *"

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Selenium Script and Update data.html
      run: |
        python data_html.py  # Bu adımda HTML içeriği doğrudan data.html dosyasına yazılacak

    - name: Commit updated data.html
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Uzak depodaki değişiklikleri çek
        git pull origin main
        
        # Değişiklik olup olmadığını kontrol et
        if git diff --quiet; then
          echo "No changes detected. Skipping commit."
        else
          git add data.html
          git commit -m "Domain URL güncellendi."  # URL güncellenmişse normal mesaj
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # kanal.yml workflow'unu tetiklemek
    - name: Trigger kanal.yml workflow
      if: ${{ success() }}  # Bu adımdan önce başarılı olursa tetiklenir
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref": "main"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/kanal.yml/dispatches
